### ISSUE TITLE
01_tidy_reshaping.Rmd : edit suggest

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/advanced-data-wrangling-in-R#10]
Ln. 257 - 265

Consider edit

 from:

        Sometimes, a consultee came to me and asked: "I don't have missing values in my original dataframe. Then R said that I have missing values after I've done some data transformations. What happened?"
        
        Here's an answer.
        
        R defines missing values in two ways.
        
        -   *Implicit missing values*: simply not present in the data.
        
        -   *Explicit missing values*: flagged with NA

to:

"People often ask: "I don't any missing values in my original dataframe, but R says I have missing values after I've done some data transformations. What's happening?"

Here's an answer.

R defines missing values in two ways.

-   *Implicit missing values*: simply not present in the data.

-   *Explicit missing values*: flagged with NA

**Comment by asteves** [comment]
Fixed
