### ISSUE TITLE
Nesting example might be overly complex for course

### ISSUE THREAD

**Issue by asteves** [dlab-berkeley/advanced-data-wrangling-in-R#17]
In the nesting section, the example using broom appears to involve several other packages that are not ramped into it solely by the course content. There's a big jump in complexity from `group_by()` to using multiple broom functions as well as `map()`

**Comment by kjhogue** [comment]
Might consider adding additional content for broom/map to ensure adequate comprehension.

**Comment by asteves** [comment]
We certainly could do that. It's just more that the nature of this workshop is pretty heavy on dplyr only. When I last taught it, most students were not familiar with dplyr. Adding in a functional programming paradigm + some statistical modeling on top of that was a lot. 

Happy to think of ways to add content and would be interested in your thoughts.

**Comment by asteves** [comment]
This is not going to be an issue in the same way for the new version of this workshop. Closing for now as a consequence.
