### ISSUE TITLE
Who should be "author" in scripts?

### ISSUE THREAD

**Issue by asteves** [dlab-berkeley/advanced-data-wrangling-in-R#19]
@EastBayEv Should the author in all of these scripts be D-Lab? Not sure what the protocol is. Right now, all of them are @jaeyk 

He should obviously continue to get credit, but it raises some confusion when other instructors teach the course initially to students.

**Comment by jaeyk** [comment]
@asteves the workshop notebooks are licensed under creative commons license, and anyone is free to modify it as long as the content remains non-commercial, and I am attributed.

**Comment by asteves** [comment]
@jaeyk Thanks. What do you think is the best way to provide attribution? 

I was thinking for the files themselves a yaml header like 

`---
title: 'Tidy Data and Reshaping'

author: "D-Lab"
...`

and then clear attribution to you for original files in the README. 

Thoughts?

**Comment by jaeyk** [comment]
@EastBayEv might know the protocol better, but attributing to me in the readme is fine enough.

**Comment by asteves** [comment]
Will follow the README option accepted by @jaeyk and updated scripts to reflect D-Lab as main author.
