### ISSUE TITLE
Issue with git clone

### ISSUE THREAD

**Issue by Akesari12** [dlab-berkeley/advanced-data-wrangling-in-R#4]
When I tried to clone the repo I ran into a fatal error that said something like "code 1/01_tidy_reshaping.Rmd.html is an invalid file path". I managed to fix it by running:

`git config --system core.longpaths true`

My best guess from [stackoverflow ](https://stackoverflow.com/questions/22041752/github-clone-succeeded-but-checkout-failed) is that there was a filename that Windows did not like. Not sure if this is fixable on our end or if end users will need to make the same adjustment.

**Comment by jaeyk** [comment]
Thanks for bringing this to my attention. I will make this issue alive for a while to see whether other people experience the same issue.

**Comment by Averysaurus** [comment]
cloned from Mac OS no probs.
