### ISSUE TITLE
oddly named file in repo

### ISSUE THREAD

**Issue by aculich** [dlab-berkeley/advanced-data-wrangling-in-R#5]
@jaeyk this seems like an oddly name file in the repo:

![image](https://user-images.githubusercontent.com/118965/94490447-1f341e00-019b-11eb-956a-76466fc99763.png)

https://github.com/dlab-berkeley/advanced-data-wrangling-in-R/blob/1f845369f5880d7e5d1e2c5cf4f16b87e5ea7804/code%5C01_tidy_reshaping.Rmd.html#L1

Should this instead be in the `code/` directory?

**Comment by jaeyk** [comment]
The file was mistakenly created and removed. Thanks for the nice catch!
