### ISSUE TITLE
Suggestion: consider removing explanation of double. 

### ISSUE THREAD

**Issue by Averysaurus** [dlab-berkeley/advanced-data-wrangling-in-R#7]
01_tidy_reshaping.Rmd
Ln. 106:110

Currently drafting instructor script: wondering since the explanation of `double precision` numeric is covered in R-fundamentals, that it may be tangential to instruction and could be removed?

**Comment by jaeyk** [comment]
@Averysaurus Please feel free to remove it. When I was the instructor of this workshop, some students asked about that concept, and that's why I included the explanation in the workshop. However, it's perhaps redundant.
